[fmt]
line_length = 120
number_underscore = 'thousands'
wrap_comments = false

[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./" }]
solc_version = "0.8.25"
build_info = true
ffi = true
ast = true
extra_output = ["storageLayout"]
evm_version = "cancun" # Compile Curve LP interface

[rpc_endpoints]
sepolia = "QUICKNODE_ENDPOINT_URL"
gnosis = "https://rpc.gnosis.gateway.fm"

[fuzz]
runs = 256

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
